trigger:
- main   # dispara la build cuando haya cambios en la rama main

pool:
  name: Default   # usa tu agente auto-hospedado del pool "Default"

steps:
# 1. Asegura Java (si lo necesitas explícito)
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '17'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'

# 2. Ejecuta Maven con la tarea oficial
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'   # ubicación del POM
    goals: 'clean install'    # objetivos de Maven
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenOptions: '-Xmx1024m'
    jdkVersionOption: '1.17'
    jdkArchitectureOption: 'x64'

